substitutions:
  _REGION: us-central1
  _REPOSITORY: sysassist
  _IMAGE: sysassist-api
  _TAG: latest

steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - deploy/docker/api.Dockerfile
      - --tag
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_TAG}
      - .

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:${_TAG}
